FROM drupal:10.5-php8.3-apache

# Install Composer (if not already present)
RUN apt-get update && apt-get install -y unzip git curl \
 && apt-get install -y --no-install-recommends rsync \
 && apt-get install -y nano cron \
 && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
 && rm -rf /var/lib/apt/lists/*