<?php

/**
 * @file
 * Contains custom form alterations and validation for fs_article content type.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\node\Entity\Node;
use Drupal\taxonomy\Entity\Term;

/**
 * Implements hook_form_FORM_ID_alter() for node FS Article forms.
 */
function fs_article_tools_form_node_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  if ($form_id === 'node_fs_article_form' || $form_id === 'node_fs_article_edit_form') {

    // Optionally call service if it exists.
    if (\Drupal::hasService('fs_article_tools.node_form_alter')) {
      $form_alter = \Drupal::service('fs_article_tools.node_form_alter');
      $form_alter->alter($form, $form_state, $form_id);
    }

    // Add custom submit handler.
    $form['actions']['submit']['#submit'][] = 'fs_article_tools_submit_handler';
  }
}


/**
 * Submit handler for FS Article form.
 */
function fs_article_tools_submit_handler(array &$form, FormStateInterface $form_state) {

  // Handling Parent Child Insertion Relation 
  if (\Drupal::hasService('fs_article_tools.mb_article_form_submit')) {
    $form_submit = \Drupal::service('fs_article_tools.mb_article_form_submit');
    $form_submit->submitForm($form, $form_state);
  }
  
}

